/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#0B3D91',
        secondary: 'rgb(96, 0, 199)',
        tertiary: '#4D7C8A',
        accent: '#00D8FF',
        'bg-dark': '#121212',
        'bg-light': '#F8F9FA',
        'bg-code': '#1E1E1E',
        'bg-code-light': '#F3F4F6',
        'text-primary-dark': '#FFFFFF',
        'text-secondary-dark': '#B0B0B0',
        'text-dark': '#333333',
        'text-light': '#F8F9FA',
        'ui-border': '#30363D',
        'ui-border-light': '#E5E7EB',
        'ui-hover': 'rgba(56, 139, 253, 0.1)',
        'ui-hover-light': 'rgba(59, 130, 246, 0.1)',
        'ui-focus': 'rgba(56, 139, 253, 0.4)',
        'ui-focus-light': 'rgba(59, 130, 246, 0.4)',
        'ui-selection': 'rgba(56, 139, 253, 0.3)',
        success: '#3FB950',
        warning: '#F7B955',
        error: '#F85149',
        info: '#58A6FF',
      },
      fontFamily: {
        body: ['"Roboto"', '"Segoe UI"', 'sans-serif'],
        heading: ['"Montserrat"', '"Segoe UI"', 'sans-serif'],
        code: ['"Fira Code"', '"Consolas"', 'monospace'],
      },
      fontSize: {
        'xs': '0.75rem',
        'sm': '0.875rem',
        'base': '1rem',
        'lg': '1.125rem',
        'xl': '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
      },
      spacing: {
        'xs': '0.25rem',
        'sm-space': '0.5rem',
        'md': '1rem',
        'lg-space': '1.5rem',
        'xl-space': '2rem',
        '2xl-space': '2.5rem',
        '3xl-space': '3rem',
      },
      screens: {
        'xs': '320px',
        'sm': '576px',
        'md': '768px',
        'lg': '992px',
        'xl': '1200px',
        '2xl': '1400px',
      },
      borderRadius: {
        'sm': '0.125rem',
        'md': '0.25rem',
        'lg': '0.5rem',
        'xl': '1rem',
        'full': '9999px',
      },
      boxShadow: {
        'sm': '0 1px 2px rgba(0, 0, 0, 0.05)',
        'md': '0 4px 6px rgba(0, 0, 0, 0.1)',
        'lg': '0 10px 15px rgba(0, 0, 0, 0.1)',
        'xl': '0 20px 25px rgba(0, 0, 0, 0.15)',
        'glow': '0 0 20px rgba(11, 61, 145, 0.3)',
        'glow-accent': '0 0 20px rgba(0, 216, 255, 0.3)',
      },
      zIndex: {
        'dropdown': '1000',
        'sticky': '1100',
        'fixed': '1200',
        'modal': '1300',
        'popover': '1400',
        'tooltip': '1500',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        twinkle: {
          '0%': { opacity: '0.2', transform: 'scale(0.8)' },
          '50%': { opacity: '1', transform: 'scale(1.1)' },
          '100%': { opacity: '0.2', transform: 'scale(0.8)' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        spin: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        gradientShift: {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
      },
      animation: {
        'fade-in': 'fadeIn 1s ease-out',
        'fade-in-delay': 'fadeIn 1s ease-out 0.3s forwards',
        'fade-in-delay-2': 'fadeIn 1s ease-out 0.6s forwards',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'twinkle': 'twinkle 3s ease-in-out infinite',
        'pulse-slow': 'pulse 1.5s ease-in-out infinite',
        'spin-slow': 'spin 1s linear infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'gradient': 'gradientShift 3s ease infinite',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(circle at center, var(--tw-gradient-stops))',
        'gradient-primary': 'linear-gradient(135deg, #0B3D91, rgb(96, 0, 199))',
        'gradient-ai': 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      },
      transitionDuration: {
        'fast': '100ms',
        'normal': '200ms',
        'slow': '300ms',
      },
    },
  },
  plugins: [],
};
